# Generated by Django 3.1.6 on 2021-02-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='ebook',
            name='author',
            field=models.CharField(default='', max_length=254),
        ),
    ]
