# Generated by Django 3.1.6 on 2021-02-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_auto_20210223_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='author',
            new_name='authors',
        ),
    ]
