# Generated by Django 3.1.6 on 2021-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_auto_20210224_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='year',
            field=models.CharField(default='', max_length=254),
        ),
    ]
